# aml/conda.yml
name: auto-pricing-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas==2.2.2
      - scikit-learn==1.5.2
      - joblib==1.4.2
      - azure-ai-ml==1.30.0
      - azure-identity==1.25.1
      - mltable==1.5.0

