name: auto-pricing-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - azure-ai-ml>=1.16.0
      - azure-identity>=1.16.0
      - pandas
      - pyarrow
      - scikit-learn
      - joblib
