name: auto-pricing-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - azure-ai-ml>=1.16.0
      - mltable>=1.4.0
      - pandas>=2.0.0
      - scikit-learn>=1.3.0
      - numpy>=1.24.0
      - joblib>=1.3.0
