$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

name: auto_pricing_pipeline
display_name: auto_pricing_pipeline
experiment_name: auto-pricing-e2e

# NOTE:
# - We rely on settings.default_compute (set by your GitHub Action with --set)
# - No 'compute_target' primitive input is used.

inputs:
  data:
    # Your UsedCars asset is a single CSV file
    type: uri_file

jobs:
  # ========= 1) TRAIN =========
  train:
    type: command

    # Paths resolved relative to this YAML (repo root is ..)
    code: ..
    environment:
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      conda_file: ../env/conda.yml

    command: >
      python scripts/train.py
      --data ${{inputs.data}}
      --output ${{outputs.model_dir}}

    inputs:
      data: ${{ parent.inputs.data }}

    outputs:
      model_dir:
        type: uri_folder
        mode: rw_mount

  # ========= 2) REGISTER =========
  register:
    type: command

    code: ..
    environment:
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      conda_file: ../env/conda.yml

    inputs:
      trained_model: ${{ parent.jobs.train.outputs.model_dir }}

    command: >
      python scripts/register.py
      --model_dir ${{inputs.trained_model}}
      --model_name auto-pricing-model
      --description "Auto Pricing model registered from pipeline"
