# aml/pipeline.yml
type: pipeline
name: auto_pricing_pipeline
description: "Train & register a simple regressor for auto pricing"
experiment_name: auto-pricing-e2e

# (Optional) You can also set a default compute here via 'settings: default_compute: ...'
# We keep it per-job for clarity.

inputs:
  training_data:
    type: uri_folder
    # This points to your registered data asset
    path: azureml:UsedCars:1
  target_column:
    type: string
    default: price
  n_estimators:
    type: integer
    default: 100
  max_depth:
    type: integer
    default: 10

jobs:
  train:
    # Inline command job (not a component reference)
    type: command
    display_name: train
    code: ../src
    command: >
      python train.py
      --data ${{inputs.training_data}}
      --target ${{inputs.target_column}}
      --n_estimators ${{inputs.n_estimators}}
      --max_depth ${{inputs.max_depth}}
      --output ${{outputs.model_dir}}
    inputs:
      training_data: ${{parent.inputs.training_data}}
      target: ${{parent.inputs.target_column}}
      n_estimators: ${{parent.inputs.n_estimators}}
      max_depth: ${{parent.inputs.max_depth}}
    outputs:
      model_dir:
        type: uri_folder
    environment:
      # IMPORTANT: this path is relative to THIS yaml file (aml/)
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240618.v1
      conda_file: ./conda.yml
    compute: azureml:${{env.AML_COMPUTE}}

  register:
    type: command
    display_name: register
    code: ../src
    command: >
      python register.py
      --model_dir ${{inputs.model_dir}}
      --model_name auto-pricing-model
    inputs:
      model_dir: ${{parent.jobs.train.outputs.model_dir}}
    environment:
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240618.v1
      conda_file: ./conda.yml
    compute: azureml:${{env.AML_COMPUTE}}
