# aml/pipeline.yml
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
name: auto-pricing-e2e
description: Train and register a RandomForest model for used car pricing

inputs:
  training_data:
    type: uri_file
  target_column:
    type: string
    default: price
  n_estimators:
    type: integer
    default: 100
  max_depth:
    type: integer
    default: 10
  model_name:
    type: string
    default: auto-pricing-model

settings:
  # YAML only accepts 'serverless' or a literal 'azureml:<compute-name>'.
  # We use 'serverless' here and override from the GitHub Action with --set.
  default_compute: serverless
  continue_on_step_failure: false

jobs:
  train:
    type: command
    component: file:components/train.yml
    inputs:
      training_data: ${{parent.inputs.training_data}}
      target_column: ${{parent.inputs.target_column}}
      n_estimators: ${{parent.inputs.n_estimators}}
      max_depth: ${{parent.inputs.max_depth}}

  register:
    type: command
    component: file:components/register.yml
    inputs:
      model_dir: ${{parent.jobs.train.outputs.model_dir}}  # creates dependency
      model_name: ${{parent.inputs.model_name}}
