# aml/pipeline.yml
# TRAIN -> REGISTER (component path fixed)

$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

name: auto_pricing_pipeline
display_name: auto_pricing_pipeline
experiment_name: auto-pricing-e2e

settings:
  default_compute: azureml:cpu-cluster   # patched to Keith-Compute at submit time
  continue_on_step_failure: false

inputs:
  data:
    type: uri_file

jobs:
  train:
    type: command
    code: ..
    environment:
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      conda_file: ../env/conda.yml
    command: >
      python scripts/train.py
      --data_path ${{ inputs.data }}
      --train_dir ${{ outputs.model_dir }}
      --metrics   ${{ outputs.metrics }}
    inputs:
      data: ${{ parent.inputs.data }}
    outputs:
      model_dir: { type: uri_folder }
      metrics:   { type: uri_file }

  register:
    type: command
    component: file:register.yaml   # path is relative to aml/
    inputs:
      model_path: ${{ jobs.train.outputs.model_dir }}
