$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: auto_pricing_pipeline
description: Train a RandomForest model on UsedCars data.

# -----------------------
# Inputs
# -----------------------
inputs:
  training_data:
    type: uri_file
    path: azureml:UsedCars:1    # registered dataset
    mode: ro_mount
  target_column: price
  n_estimators: 100
  max_depth: 10

# -----------------------
# Settings
# -----------------------
settings:
  # Must be 'serverless' or 'azureml:<compute-short-name>'
  default_compute: azureml:Keith-Compute
  continue_on_step_failure: false

# -----------------------
# Pipeline jobs
# -----------------------
jobs:
  train:
    type: command
    # NOTE: your CI workflow auto-patches this to the newest version on each run
    component: azureml:train_random_forest:1
    inputs:
      training_data:  ${{ parent.inputs.training_data }}
      target_column:  ${{ parent.inputs.target_column }}
      n_estimators:   ${{ parent.inputs.n_estimators }}
      max_depth:      ${{ parent.inputs.max_depth }}
    outputs:
      # Make the output contracts explicit so downstream steps (if added later) can bind reliably
      model_dir:
        type: uri_folder
        mode: rw_mount
      metrics:
        type: uri_file
        mode: rw_mount
