$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: auto_pricing_pipeline
experiment_name: auto-pricing-e2e

settings:
  default_compute: azureml:Keith-Compute
  continue_on_step_failure: false

inputs:
  data:
    type: uri_file  # your data asset azureml:UsedCars:1 will be bound to this

jobs:
  train:
    type: command
    # IMPORTANT: make repo root the code context (pipeline.yml is under aml/)
    code: ..
    environment:
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240618.v1
      # Path is relative to the code context above (repo root)
      conda_file: aml/conda.yml
    command: >-
      python scripts/train.py
      --data ${{inputs.data}}
      --target price
      --n_estimators 100
      --max_depth 10
      --model_dir ${{outputs.model_dir}}
      --metrics ${{outputs.metrics}}
    inputs:
      data: ${{parent.inputs.data}}
    outputs:
      model_dir: {}
      metrics: {}

  register:
    type: command
    code: ..
    environment:
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240618.v1
      conda_file: aml/conda.yml
    command: >-
      python scripts/register.py
      --model_dir ${{inputs.model_dir}}
      --model_name auto-pricing-model
    inputs:
      model_dir: ${{parent.jobs.train.outputs.model_dir}}
