$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: auto_pricing_pipeline
description: Train a RandomForest model on UsedCars data.

# -----------------------
# Inputs
# -----------------------
inputs:
  training_data:
    type: uri_file
    # quote because the value contains colons
    path: "azureml:UsedCars:1"
  target_column:
    type: string
    default: price
  n_estimators:
    type: integer
    default: 100
  max_depth:
    type: integer
    default: 10

# -----------------------
# Settings
# -----------------------
settings:
  # Will be auto-patched by CI if needed
  default_compute: azureml:Keith-Compute
  continue_on_step_failure: false

# -----------------------
# Pipeline jobs
# -----------------------
jobs:
  train:
    type: command
    # CI will auto-bump this version
    component: azureml:train_random_forest:1
    inputs:
      training_data:  ${{ parent.inputs.training_data }}
      target_column:  ${{ parent.inputs.target_column }}
      n_estimators:   ${{ parent.inputs.n_estimators }}
      max_depth:      ${{ parent.inputs.max_depth }}
    outputs:
      model_dir:
        type: uri_folder
      metrics:
        type: uri_file
