type: pipeline
name: auto_pricing_pipeline
description: Train a RandomForest on UsedCars and register the model.

# run everything on your cluster
settings:
  default_compute: azureml:Keith-Compute

# pipeline-level inputs (filled from az ml job create --set ...)
inputs:
  data:
    type: mltable
  target_column:
    type: string
  n_estimators:
    type: integer
  max_depth:
    type: integer

jobs:
  train:
    type: command
    code: .
    command: >-
      python aml/train.py
      --data ${{inputs.data}}
      --target_column ${{inputs.target_column}}
      --n_estimators ${{inputs.n_estimators}}
      --max_depth ${{inputs.max_depth}}
      --output_dir ${{outputs.model_dir}}
    environment:
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240618.v1
      conda_file: aml/conda.yml
    inputs:
      data: ${{parent.inputs.data}}
      target_column: ${{parent.inputs.target_column}}
      n_estimators: ${{parent.inputs.n_estimators}}
      max_depth: ${{parent.inputs.max_depth}}
    outputs:
      model_dir:
        mode: rw_mount
        type: uri_folder

  register:
    type: command
    code: .
    command: >-
      python aml/register.py
      --model_dir ${{inputs.model_dir}}
      --model_name auto-pricing-model
    environment:
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240618.v1
      conda_file: aml/conda.yml
    inputs:
      model_dir: ${{parent.jobs.train.outputs.model_dir}}
