$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: auto_pricing_pipeline
experiment_name: auto-pricing-e2e

settings:
  default_compute: azureml:Keith-Compute
  continue_on_step_failure: false

inputs:
  data:
    type: uri_file  # bound from the workflow: azureml:UsedCars:1

jobs:
  train:
    type: command
    # pipeline.yml sits in aml/, so '..' makes the repo root the code context
    code: ..
    environment:
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240618.v1
      # IMPORTANT: path is relative to *this* YAML's folder (aml/), so just 'conda.yml'
      conda_file: conda.yml
    command: >-
      python scripts/train.py
      --data ${{inputs.data}}
      --target price
      --n_estimators 100
      --max_depth 10
      --model_dir ${{outputs.model_dir}}
      --metrics ${{outputs.metrics}}
    inputs:
      data: ${{parent.inputs.data}}
    outputs:
      model_dir: {}
      metrics: {}

  register:
    type: command
    code: ..
    environment:
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240618.v1
      # same fix here
      conda_file: conda.yml
    command: >-
      python scripts/register.py
      --model_dir ${{inputs.model_dir}}
      --model_name auto-pricing-model
    inputs:
      model_dir: ${{parent.jobs.train.outputs.model_dir}}
