# aml/pipeline.yml
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
description: Auto pricing end-to-end training + register

settings:
  default_compute: "azureml:Keith-Compute"   # <-- quote values containing a colon
  continue_on_step_failure: false

inputs:
  training_data:
    type: mltable
    path: "azureml:UsedCars:1"               # <-- quote values containing a colon
  target_column:
    type: string
    default: price
  n_estimators:
    type: integer
    default: 100
  max_depth:
    type: integer
    default: 10
  model_name:
    type: string
    default: auto-pricing-model

jobs:
  train:
    type: command
    component: file: ./components/train.yml
    inputs:
      training_data: ${{parent.inputs.training_data}}
      target_column: ${{parent.inputs.target_column}}
      n_estimators: ${{parent.inputs.n_estimators}}
      max_depth: ${{parent.inputs.max_depth}}
    outputs:
      model_dir: {}
      metrics: {}

  register:
    type: command
    component: file: ./components/register.yml
    inputs:
      model_dir: ${{parent.jobs.train.outputs.model_dir}}
      model_name: ${{parent.inputs.model_name}}
    depends_on:
      - train
