$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: auto_pricing_pipeline
description: Train a model and register it.

inputs:
  training_data:
    type: uri_file
    path: azureml:UsedCars:1   # ✅ your existing File (uri_file) asset
    mode: ro_mount
  target_column: price
  n_estimators: 100
  max_depth: 10
  model_name: auto-pricing-model

settings:
  default_compute: serverless

jobs:
  train:
    type: command
    component: file:components/train.yml
    inputs:
      training_data: ${{parent.inputs.training_data}}
      target_column:  ${{parent.inputs.target_column}}
      n_estimators:   ${{parent.inputs.n_estimators}}
      max_depth:      ${{parent.inputs.max_depth}}
    outputs:
      model_dir:
      metrics:

  register:
    type: command
    component: file:components/register.yml
    inputs:
      model_dir:  ${{parent.jobs.train.outputs.model_dir}}
      model_name: ${{parent.inputs.model_name}}
