$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: auto_pricing_pipeline
description: Train a RandomForest model on UsedCars data.

inputs:
  training_data:
    type: uri_file
    path: "azureml:UsedCars:1"   # data asset → keep type
    mode: ro_mount
  target_column: price           # literal params → no "type", no "default"
  n_estimators: 100
  max_depth: 10

settings:
  default_compute: azureml:Keith-Compute
  continue_on_step_failure: false

jobs:
  train:
    type: command
    component: azureml:train_random_forest:1   # CI will bump this
    inputs:
      training_data:  ${{ parent.inputs.training_data }}
      target_column:  ${{ parent.inputs.target_column }}
      n_estimators:   ${{ parent.inputs.n_estimators }}
      max_depth:      ${{ parent.inputs.max_depth }}
    outputs:
      model_dir:
        type: uri_folder
      metrics:
        type: uri_file
