# aml/pipeline.yml
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
description: Auto pricing end-to-end training + register

settings:
  default_compute: azureml:Keith-Compute   # <-- change if your compute name is different
  continue_on_step_failure: false

inputs:
  # Change to your data asset if different
  training_data: azureml:UsedCars:1
  target_column: price
  n_estimators: 100
  max_depth: 10
  model_name: auto-pricing-model

jobs:
  train:
    type: command
    component: file: ./components/train.yml
    inputs:
      training_data: ${{parent.inputs.training_data}}
      target_column: ${{parent.inputs.target_column}}
      n_estimators: ${{parent.inputs.n_estimators}}
      max_depth: ${{parent.inputs.max_depth}}
    outputs:
      model_dir: {}
      metrics: {}

  register:
    type: command
    component: file: ./components/register.yml
    inputs:
      model_dir: ${{parent.jobs.train.outputs.model_dir}}
      model_name: ${{parent.inputs.model_name}}
    depends_on:
      - train
