$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: auto_pricing_pipeline
experiment_name: auto-pricing-e2e

settings:
  default_compute: azureml:Keith-Compute
  continue_on_step_failure: false

inputs:
  data:
    type: uri_file
    mode: ro_mount   # stream the csv
  target_column:
    type: string
    default: price
  n_estimators:
    type: integer
    default: 100
  max_depth:
    type: integer
    default: 10

jobs:
  train:
    type: command
    code: .
    command: >-
      python scripts/train.py
      --data ${{inputs.data}}
      --target ${{inputs.target_column}}
      --n_estimators ${{inputs.n_estimators}}
      --max_depth ${{inputs.max_depth}}
      --model_dir ${{outputs.model_dir}}
      --metrics ${{outputs.metrics}}
    environment:
      build:
        image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240618.v1
        conda_file: aml/conda.yml
    inputs:
      data: ${{parent.inputs.data}}
      target_column: ${{parent.inputs.target_column}}
      n_estimators: ${{parent.inputs.n_estimators}}
      max_depth: ${{parent.inputs.max_depth}}
    outputs:
      model_dir:
        mode: rw_mount
      metrics:
        mode: rw_mount

  register:
    type: command
    code: .
    command: >-
      python scripts/register.py
      --model_dir ${{inputs.model_dir}}
      --model_name auto-pricing-model
    environment:
      build:
        image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240618.v1
        conda_file: aml/conda.yml
    inputs:
      model_dir: ${{parent.jobs.train.outputs.model_dir}}
