$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: TrainRandomForest
version: 1
type: command
display_name: Train RandomForest
description: Train a RandomForestRegressor and output a pickle + metrics

# NOTE: path is RELATIVE TO THIS FILE (components/train.yml)
code: ../src/train

# Use a curated, supported environment with scikit-learn
environment: azureml://registries/azureml/environments/sklearn-1.2/labels/latest

inputs:
  training_data:
    type: uri_file
  target_column:
    type: string
  n_estimators:
    type: integer
  max_depth:
    type: integer

outputs:
  model_dir:
    type: uri_folder
  metrics:
    type: uri_folder

command: >-
  python train.py
  --data ${{inputs.training_data}}
  --target ${{inputs.target_column}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --output ${{outputs.model_dir}}
  --metrics ${{outputs.metrics}}
