$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json

name: train_random_forest
display_name: Train RandomForest
type: command
version: 3   # bump whenever you change this file

inputs:
  training_data:
    type: uri_file         # CSV file (uri_file)
  target_column:
    type: string
  n_estimators:
    type: integer
  max_depth:
    type: integer

outputs:
  model_dir:
    type: uri_folder
  metrics:
    type: uri_folder

# Source code (train.py is here)
code: .

# ✅ Use a curated Azure ML environment (no image/conda here)
#   This exists in every region and avoids "image does not exist" errors.
environment: azureml://registries/azureml/environments/sklearn-1.3/versions/4

command: >-
  python train.py
  --data ${{inputs.training_data}}
  --target ${{inputs.target_column}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --output ${{outputs.model_dir}}
  --metrics_out ${{outputs.metrics}}
