$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: TrainRandomForest
display_name: Train RandomForest
type: command

# component-level inputs/outputs (types are correct here)
inputs:
  training_data:
    type: uri_file
  target_column:
    type: string
  n_estimators:
    type: integer
  max_depth:
    type: integer
outputs:
  model_dir:
    type: uri_folder
  metrics:
    type: uri_folder

# your training script (relative to THIS yaml)
code: ./src/train

# make the environment self-contained
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240618.v1
  conda_file: ../env/conda.yml

# pass args to script
command: >-
  python train.py
  --data ${{inputs.training_data}}
  --target ${{inputs.target_column}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --output ${{outputs.model_dir}}
  --metrics_out ${{outputs.metrics}}
