$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: TrainRandomForest
display_name: Train RandomForest
type: command
version: 1

inputs:
  training_data:
    type: uri_file          # ✅ CSV file via URI
  target_column:
    type: string
  n_estimators:
    type: integer
  max_depth:
    type: integer

outputs:
  model_dir:
    type: uri_folder
  metrics:
    type: uri_folder

code: .

environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240618.v1
  conda_file: ../env/conda.yml

command: >-
  python train.py
  --data ${{inputs.training_data}}
  --target ${{inputs.target_column}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --output ${{outputs.model_dir}}
  --metrics_out ${{outputs.metrics}}
