$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_random_forest              # must be lowercase, letters/numbers/underscores
display_name: Train RandomForest
type: command
version: 1

inputs:
  training_data:
    type: uri_file                      # single CSV file
  target_column:
    type: string
  n_estimators:
    type: integer
  max_depth:
    type: integer

outputs:
  model_dir:
    type: uri_folder
  metrics:
    type: uri_folder

code: .

# ✅ Use a public Microsoft image that exists in all regions
#    (no curated env dependency)
environment:
  image: mcr.microsoft.com/azureml/sklearn-1.3-ubuntu20.04-py38-cpu:latest
  # If you need extra pip packages, uncomment the next line and provide env/conda.yml
  # conda_file: ../env/conda.yml

command: >-
  python train.py
  --data ${{inputs.training_data}}
  --target ${{inputs.target_column}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --output ${{outputs.model_dir}}
  --metrics_out ${{outputs.metrics}}
