$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_random_forest
version: 0                       # <— the CI workflow will overwrite this
display_name: Train RandomForest
type: command

# Snapshot the whole repo so train.py is guaranteed to be included.
# (If you prefer, set this to the folder that actually contains train.py.)
code: .

# The workflow will also overwrite/ensure `environment:` exists.
# If you want to pin it here yourself, you can put:
# environment: azureml:keith-sklearn-ci:<version>

inputs:
  training_data:
    type: uri_file
  target_column:
    type: string
  n_estimators:
    type: integer
  max_depth:
    type: integer

outputs:
  model_dir:
    type: uri_folder
  metrics:
    type: uri_file

command: >
  python aml/components/train.py
  --data ${{inputs.training_data}}
  --target ${{inputs.target_column}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --output ${{outputs.model_dir}}
  --metrics_out ${{outputs.metrics}}
