# aml/components/train.yml
$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_randomforest
version: 1
type: command
display_name: Train RandomForest
description: Train a RandomForest regressor and output model + metrics

# NOTE: this path is relative to this YAML (aml/components/)
code: ../src/train

# Curated AzureML environment
environment: azureml://registries/azureml/environments/AzureML-sklearn-1.2-ubuntu20.04-py38-cpu/labels/latest

inputs:
  training_data:
    type: uri_file
  target_column:
    type: string
  n_estimators:
    type: integer
    default: 100
  max_depth:
    type: integer
    default: 10

outputs:
  model_dir:
    type: uri_folder
  metrics:
    type: uri_folder

command: >-
  python train.py
  --data ${{inputs.training_data}}
  --target ${{inputs.target_column}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --output ${{outputs.model_dir}}
  --metrics_out ${{outputs.metrics}}
