$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_random_forest
display_name: Train RandomForest
type: command
version: 1

inputs:
  training_data:
    type: uri_file
  target_column:
    type: string
  n_estimators:
    type: integer
  max_depth:
    type: integer

outputs:
  model_dir:
    type: uri_folder
  metrics:
    type: uri_folder

code: .

# ✅ Use a stable Microsoft base image available in all regions
#    and add our small conda env for pandas/sklearn/joblib.
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1-ubuntu20.04:latest
  conda_file: ../env/conda.yml

command: >-
  python train.py
  --data ${{inputs.training_data}}
  --target ${{inputs.target_column}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --output ${{outputs.model_dir}}
  --metrics_out ${{outputs.metrics}}
