$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_random_forest
display_name: Train RandomForest
type: command

inputs:
  training_data:
    type: uri_file
  target_column:
    type: string
  n_estimators:
    type: integer
  max_depth:
    type: integer

outputs:
  model_dir:
    type: uri_folder
  metrics:
    type: uri_folder

code: .

# 👇 Use a curated environment from the AzureML registry (region-available)
# If your workspace doesn't have this exact version, any recent version works.
environment: azureml:AzureML-sklearn-1.3-ubuntu22.04-py310-cpu:16

command: >-
  python train.py
  --data ${{inputs.training_data}}
  --target ${{inputs.target_column}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --output ${{outputs.model_dir}}
  --metrics_out ${{outputs.metrics}}
