$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: Train_RandomForest
display_name: Train RandomForest
type: command

inputs:
  training_data:
    type: uri_file
  target_column:
    type: string
  n_estimators:
    type: integer
    default: 100
  max_depth:
    type: integer
    default: 10

outputs:
  model_dir:
    type: uri_folder
  metrics:
    type: uri_file

# point to your training source folder that contains train.py
code: ../src/train

# ✅ Use a curated AzureML environment (no build needed)
# If this specific version isn't available in your region, see the note at the end.
environment: azureml://registries/azureml/environments/sklearn-1.3/versions/9

command: >-
  python train.py
  --data ${{inputs.training_data}}
  --target ${{inputs.target_column}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --output ${{outputs.model_dir}}
  --metrics ${{outputs.metrics}}
