$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_random_forest
version: 0                       # CI can overwrite this
display_name: Train RandomForest
type: command

# If CI doesn't inject an environment, uncomment one of these:
# environment: azureml://registries/azureml/environments/sklearn-1.0/labels/latest
# environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest

# Snapshot the whole repo so train.py is guaranteed to be included.
code: .

inputs:
  training_data:
    type: uri_file
  target_column:
    type: string
  n_estimators:
    type: integer
  max_depth:
    type: integer

outputs:
  model_dir:
    type: uri_folder
  metrics:
    type: uri_folder   # ← CHANGED from uri_file → uri_folder to match train.py

command: >
  python aml/components/train.py
  --data ${{inputs.training_data}}
  --target ${{inputs.target_column}}
  --n_estimators ${{inputs.n_estimators}}
  --max_depth ${{inputs.max_depth}}
  --output ${{outputs.model_dir}}
  --metrics_out ${{outputs.metrics}}

resources:
  instance_count: 1
