name: rf-train-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - scikit-learn==1.3.2
      - pandas>=1.5
      - joblib
      - mlflow
      - azure-ai-ml>=1.15.0
