name: auto-pricing-mlops
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - azure-ai-ml==1.20.0
      - mlflow==2.16.0
      - scikit-learn==1.5.2
      - pandas==2.2.2
      - numpy==1.26.4
      - joblib==1.4.2
      - matplotlib==3.9.0
      - pyarrow==17.0.0
      - fastparquet==2024.5.0