# env/conda.yml  (FULL REPLACEMENT)

name: auto-pricing-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      # Azure ML SDK + runtime
      - azure-ai-ml
      - azureml-core
      - azureml-defaults

      # Experiment tracking
      - mlflow

      # Modeling stack
      - scikit-learn
      - pandas
      - numpy
      - joblib

      # (Optional but harmless; improves parquet/csv robustness)
      - pyarrow
